### ISSUE TITLE
Coverage files not created when singleRun is true

### ISSUE THREAD

**Issue by gwin003** [karma-runner/karma-coverage#107]
I am using Karma to run my unit tests and am now trying to incorporate karma-coverage into my process. I am using PhantomJS to run the tests with singleRun: true. Whenever I do this, my code coverage reporter does not seem to be running. If I set singleRun: false, the folder and files are created.

I think this might be a bug? I cannot seem to find any information on it.

Here is my config file:

    module.exports = function (config) {
     config.set({
      basePath: '',
      frameworks: ['mocha', 'requirejs', 'sinon-chai'],
      files: [
        { pattern: 'bower_components/angular/angular.js', included: false },
        { pattern: 'bower_components/jquery/dist/jquery.js', included: false },
        { pattern: 'bower_components/angular-mocks/angular-mocks.js', included: false },
        { pattern: '**/*.js', included: false },
        { pattern: 'KarmaTests/test-main.js', included: true },
        { pattern: 'KarmaTests/**/*Test*.js', included: false }
       ],

      preprocessors: {
          'KarmaTests/*/*.js': ['coverage']
      },

      reporters: ['progress', 'coverage'],

      coverageReporter: {
          type: 'html',
          dir: '_testCoverage/',
          file: 'cover.html'
      },

      port: 9876,
      colors: true,
      logLevel: config.LOG_INFO,
          autoWatch: true,

          browsers: ['PhantomJS'],

          //files are created when false, are not when true
          singleRun: false
      });
    };

My versions are "karma": "^0.12.24" and "karma-coverage": "0.1.2".

**Comment by Dignifiedquire** [comment]
Is this still an issue?

**Comment by gwin003** [comment]
It seems to work fine when running my tests through a gulp task, so either I had something wrong before or its fixed now. Feel free to close this for now since it doesn't seem like anyone else has experienced the problem

**Comment by Dignifiedquire** [comment]
Thanks for the quick response @gwin003
