### ISSUE TITLE
Sourcemaps support

### ISSUE THREAD

**Issue by mwisnicki** [karma-runner/karma-coverage#109]
Can you add support for sourcemaps ?

**Comment by dayyan** [comment]
:+1: It would be nice to see where in my coffee script source errors are occurring.

**Comment by GoulwenBZH** [comment]
:+1:  same thing for typescript code after tsify/browserify.

**Comment by Gigitsu** [comment]
How is this supposed to work? I'm having problem with typescript, coverage preprocessor strips away every sourceMappingURL comment from my js files

**Comment by vsakaria** [comment]
I am having problems to with karma-coverage and sourcemaps used in grunt-karma. Any idea's??
