### ISSUE TITLE
npm install warning

### ISSUE THREAD

**Issue by jmullo** [karma-runner/karma-coverage#113]
npm WARN package.json karma-coverage@0.2.6 No README data

This annoys me greatly.

**Comment by jshemas** [comment]
+1

**Comment by eddiemonge** [comment]
PR it. its an easy change

**Comment by jshemas** [comment]
@eddiemonge: There all ready is a read me... The owner needs to publish the latest package to NPM.

**Comment by zzo** [comment]
done
