### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by vitalybe** [karma-runner/karma-coverage#120]
I'm trying to get karma-coverage to work with TypeScript, but so far I fail:

I am getting a coverage report for a .ts file, however, there the syntax-highlighting is completely wrong. It would be perfectly fine if I could see the coverage on the JS version of the .ts file, but right now, I don't seem to be able to get that.

**Comment by tkrotoff** [comment]
+1 for this feature

**Comment by svemir** [comment]
I see that the related pull request for instrumenters has been merged already. Is that supposed to solve this (once we install a typescript instrumenter?) or there is more work to do?

**Comment by stramel** [comment]
Is there a Typescript instrumenter similar to the [Coffeescript one](https://github.com/Constellation/ibrik)?

**Comment by loicoudot** [comment]
With AngularJS 2.0 and Typescript support comming : +1 for this feature

**Comment by hourliert** [comment]
+1 :+1:

**Comment by crabl** [comment]
+1

**Comment by iegorov** [comment]
+1

**Comment by Dignifiedquire** [comment]
I'm closing this issue as this is not something that karma-coverage itself can do, you can use different instrumenters, so you have to find an instrumenter that supports typescript to generate coverage reports for it.
