### ISSUE TITLE
CoffeScript coverage after concat and UglifyJS

### ISSUE THREAD

**Issue by kuraga** [karma-runner/karma-coverage#121]
Good day!

I use `gulp` with plugins which:
1) `.coffee` compile to `.js`,
2) concat all files in one,
3) uglify it,
4) a sourcemap can be generated.

Do I have a chance to generate a coverage of original coffeescript code using `karma-coverage`?
I have seen #16, #19, #109 but don't have a straight answer.
Thanks!

**Comment by Dignifiedquire** [comment]
Hey, 
sorry for the late reply did you manage to get it running?

**Comment by kuraga** [comment]
Don't remember, sorry.

**Comment by kuraga** [comment]
I didn't remember.

Note that the original problem hasn't been resolved (referenced issues' state proofs that) but I just can't reproduce as I don't use `karma` anymore.
