### ISSUE TITLE
Please allow reporting main stats in command line

### ISSUE THREAD

**Issue by bwest87** [karma-runner/karma-coverage#128]
Hi, karma-coverage is great so far, with one substantial exception. There doesn't appear to be a way to log the main coverage stats to the console when you're running Karma. 
Specifically, I'd love to see something like...
```
  karma start karma.conf.js
  ..............
  Done, without errors.
  Coverage Report:
  Statements: 81.94% 
  Branches: 87.43 %
  Functions: 90.91%
  Lines: 85.88%
  Ignored: None
```

I haven't looked extensively through the source, but it seems like this could be trivial to add, and it would be really helpful, so you don't have to open the html file each time, and get some feedback as you go.

Thanks! - PS: Adding a delta from the last test run could be cool too.

**Comment by EvilOatmeal** [comment]
You can get this using the "text-summary" reporter (read about the `coverageReporter` option).

It will output a report that looks like this:
```
========== Coverage summary ==========
Statements   : 13.9% ( 939/6756 )
Branches     : 5.91% ( 152/2572 )
Functions    : 17.68% ( 294/1663 )
Lines        : 12.62% ( 584/4628 )
======================================
```

**Comment by jodytate** [comment]
using @EvilOatmeal's pointer, i was able to get output to the command line using this option configuration: 

    coverageReporter: {
      type : 'text-summary'
    },

Note, if you remove these lines...

      dir : 'coverage/',
      file : 'coverage.txt'
    }

then `text-summary` outputs to the console
