### ISSUE TITLE
html reports have no data on current master branch

### ISSUE THREAD

**Issue by mwinche** [karma-runner/karma-coverage#132]
The short of this is that if you run an html coverage reporter it will have no data. I set up a simple module to demonstrate this: https://github.com/mwinche/karma-html-report-bug

Follow steps in the README.md to duplicate.

**Comment by daniellmb** [comment]
+1

**Comment by mwinche** [comment]
Luckily I've only seen this on master, not in any official releases. Are you seeing this in released code or only in master as well?

**Comment by daniellmb** [comment]
v0.3.1

**Comment by Lalem001** [comment]
In my experimentation, the issue appears to only occur if `text` or `text-summary` is the first reporter.

**Comment by uglow** [comment]
+1, only on v0.3.1.  Confirmed that 0.2.7 and 0.3.0 do NOT have this issue.

**Comment by mwinche** [comment]
PR to fix this has been merged :smile:

**Comment by Dignifiedquire** [comment]
Published as `0.4.0` :)

**Comment by mwinche** [comment]
:+1:
