### ISSUE TITLE
CSS Main Style Paths is not relative on tested js functions

### ISSUE THREAD

**Issue by inquire** [karma-runner/karma-coverage#135]
As istanbul creates an html file with highlights on the lines of code that have been tested or not tested,  The latest version  0.2.7 only refers to the style css as style.css and does not have a relative path. Version 0.2.5 works well.

I am testing this on Windows 7 with the phantom.js headless browser. I believe the code that generates the relative path of the css styles has a bug in there somewhere.

**Comment by gonzofish** [comment]
+1

**Comment by SquadraCorse** [comment]
+1
confirmed. Version 0.2.5 worked on osx & windows. Version 0.2.7 sets css path wrong, only first view is rendered correctly

**Comment by juangabreil** [comment]
This bug is related to istanbul, see: https://github.com/gotwarlost/istanbul/issues/79 and https://github.com/gotwarlost/istanbul/issues/315

**Comment by felixbillon** [comment]
+1

**Comment by mbcooper** [comment]
+1

**Comment by TwitchBronBron** [comment]
+1

**Comment by jshthornton** [comment]
+1

**Comment by rvignacio** [comment]
I can confirm that @juangabreil's pull request gotwarlost/istanbul#320 fixed the problem, this issue should be closed since it was never related to karma-coverage.
