### ISSUE TITLE
NPM package release

### ISSUE THREAD

**Issue by hiebj** [karma-runner/karma-coverage#136]
Not sure if an issue is really the right place for this, but I was wondering when you planned to publish the latest to your NPM package. There has been a pull request incorporated since the last release that I needed, and I have been pointing to the github repo ever since. It's not a major problem but NPM can't check versions against github, so it downloads the latest every time I run `npm install`.

**Comment by mairatma** [comment]
+1

**Comment by adam-beck** [comment]
+1

**Comment by jshemas** [comment]
+1

**Comment by banjankri** [comment]
+1

**Comment by jasonslyvia** [comment]
+1

**Comment by zzo** [comment]
done
