### ISSUE TITLE
Coverage threshold colors doent work for me

### ISSUE THREAD

**Issue by FJLopezGarcia** [karma-runner/karma-coverage#139]
Hi all, 
I have added to mt Karma.conf the Coverage threshold as you can see below... but after running the colors are not apply. Do you know the reason? i am ussing "karma-coverage": "~0.2.7",

        coverageReporter: {
            //Coverage threshold colors: 
            //- The first number is the threshold between Red and Yellow. 
            //- The second number is the threshold between Yellow and Green.
            watermarks: {
                statements: [50,75],
                lines: [50,75],
                functions: [50,75],
                branches:[50,75]
            },
            reporters: [
              {
                  type: 'html',
                  dir: 'app/tests/coverage/'
              },
              //{ type: 'text-summary' , dir: 'app/tests/coverage/'},
              {
                  type: 'text',
                  dir: 'app/tests/coverage/'
              }
            ],
        }

**Comment by stramel** [comment]
I think yours needs to go under the `html` reporter.

```js
coverageReporter: {
  reporters: [
    {
      type: 'html',
      dir: 'app/tests/coverage',
      watermarks: {
        statements: [50,75],
        lines: [50,75],
        functions: [50,75],
        branches:[50,75]
     }
  ]
}
```

**Comment by FJLopezGarcia** [comment]
Muchas gracias!!! Thanks a lot. It works great
