### ISSUE TITLE
With a directory specified, files are being generated along with .js files

### ISSUE THREAD

**Issue by luisrudge** [karma-runner/karma-coverage#14]
I'm using this config:
```javascript
    coverageReporter: {
        type : 'html',
        dir : '../coverage/'
    },
    preprocessors: {
        '../../Ccee/js/way2.filtroDePontos.js': 'coverage',
        '../../Ccee/js/models/*.js': 'coverage',
        '../../Ccee/js/views/*.js': 'coverage',
        '../../Ccee/js/viewmodels/*.js': 'coverage'
    }
```
Since i have specified a directory for my coverage, then why files are being created along with my .js files?
![image](https://f.cloud.github.com/assets/941075/1050530/620be2a4-10bb-11e3-9cca-1a3ef19e86d8.png)

This is pretty annoying. Shouldn't all this files be inside my /coverage folder?

**Comment by Dignifiedquire** [comment]
Is this still an issue with the latest version?

**Comment by ath0mas** [comment]
Yes, same problem here with any version (from ~0.1 to latest 0.4.2)
Tested with karma@~0.10 and karma@~0.9

Windows 7, Node 0.12.6

**Comment by ath0mas** [comment]
OK on Linux

**Comment by vkareh** [comment]
I can confirm this is fixed for me on Windows 7 when using 0.5.1, as referenced in #172
Here is my config:
```js
{
  basePath: '../',
  files: [
    // snip...
    "src/app/**/*.js",
  ],
  reporters: ['progress', 'html', 'coverage'],
  htmlReporter: {
    outputDir: 'testReports/result/'
  },
  preprocessors: {
    'src/app/**/*.js': ['coverage']
  },
  coverageReporter: {
    reporters: [{
      type: 'text'
    }, {
      type: 'html',
      dir: 'testReports/coverage'
    }]
  }
}
```

**Comment by Dignifiedquire** [comment]
Thanks guys :)

**Comment by ath0mas** [comment]
Thanks 👍
works great with same config as I used before
