### ISSUE TITLE
karma-coverage don't minify sources

### ISSUE THREAD

**Issue by FloNeu** [karma-runner/karma-coverage#149]
First things first, thx for this greate tool! Love it!
But... :) I currently had to split my karma-configuration into one for running
to perform tests and one for producing the coverage, because the karma-coverage
plugin seems to minify the used sources, wich is a pain if you want to debug tested sources
in Browser Dev-Tools.
Can you remove this behaviour, or provide a option to disable minification?

Thx in advance, Florian!

**Comment by nathanlundquist** [comment]
+1

**Comment by nmalaguti** [comment]
You can pass an option in that will cause the code not to be compacted:

```javascript
coverageReporter: {
  instrumenterOptions: {
    istanbul: { noCompact: true }
  }
}
```

I have an open PR #146 that will add sourcemap support to the instrumenter to make debugging instrumented code easier, but it is blocked on a PR on Istanbul https://github.com/gotwarlost/istanbul/pull/349.

**Comment by HipsterZipster** [comment]
+1 this is a big one

**Comment by Dignifiedquire** [comment]
@nmalaguti it would be great if you could put that info into the Readme in a `FAQ` section

**Comment by goneale** [comment]
Doesn't help a great deal, yes minification has been turned off, but obfuscation is still on... Anyway to turn this off as well?
```
$scope.eventRender = function (event, element, view) {
                        __cov_mT96vWK9Cuv6HEhBTJJ2GA.f['42']++;
                        __cov_mT96vWK9Cuv6HEhBTJJ2GA.s['144']++;
                        debugger;
                        __cov_mT96vWK9Cuv6HEhBTJJ2GA.s['145']++;
                        var isFastabookBooking = event.type === 1;
                        __cov_mT96vWK9Cuv6HEhBTJJ2GA.s['146']++;
                        element.addClass('bk');
                        __cov_mT96vWK9Cuv6HEhBTJJ2GA.s['147']++;
                        element.attr({
                            'tooltip': event.customer,
                            'tooltip-append-to-body': true
                        });
```

**Comment by urecio** [comment]
@goneale have a look here: http://stackoverflow.com/questions/30470796/function-equality-assertion-broken-by-code-coverage-report/34633935#34633935

Hope this helps

**Comment by dgreene1** [comment]
Wow, the fact that it still obfuscates the code is a real bummer. I think it's safe to say that this issue should be reopened...?

**Comment by vegar** [comment]
It's not obfuscated, is it?
The original code is there in clear text.
It's just that the tool have inserted a lot of extra 'obscure' code to do coverage calculation?
