### ISSUE TITLE
Instructions outdated

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [karma-runner/karma-coverage#153]
The install instructions in the readme.md are:

```json
{
  "devDependencies": {
    "karma": "~0.10",
    "karma-coverage": "~0.1"
  }
}
```

This gave me a greatly outdated version and I encountered a bug which was already fixed (issue #71). The install instructions should include the latest stable version.

**Comment by Dignifiedquire** [comment]
I removed that section, that way it's never outdated ;)
