### ISSUE TITLE
coffeescript ignore coverage doesn't work

### ISSUE THREAD

**Issue by artmees** [karma-runner/karma-coverage#154]
in the following example

    ### istanbul ignore else ###
    toast.error response.data.title if response.data

the coverage reporter doesn't ignore the else path
resulting in the following 
![screen shot 2015-05-27 at 11 20 50 pm](https://cloud.githubusercontent.com/assets/347712/7847896/78df3a44-04cf-11e5-9ffa-10be8b14d57d.png)

I've tried to change the code and the comment in many various ways but non of them worked... I'm wondering if ignore path is working at all ?!

**Comment by Dignifiedquire** [comment]
This sounds like an issue with Istanbul, not with the karma-coverage plugin, please file an issue there.
