### ISSUE TITLE
Reporter ignoring configuration on file change or karma run

### ISSUE THREAD

**Issue by mmacedo** [karma-runner/karma-coverage#165]
My settings are somewhat like this (karma 0.12.37 and karma-coverage 0.4.2):

```js
module.exports = function(config) {
  config.set({
    files: [ 'src/*.js', 'test/*.js' ] ,
    frameworks: [ 'jasmine' ],
    browsers: [ 'PhantomJS' ],
    reporters: [ 'coverage' ],
    preprocessors: {
      'src/*.js': [ 'coverage' ]
    },
    coverageReporter: {
      dir: 'tmp/coverage',
      reporters: [
        { type: 'html', subdir: 'report-html' },
        { type: 'lcov', subdir: 'report-lcov' }
      ]
    }
  });
};
```

If I execute `karma start --single-run` it generates the html report on `tmp/coverage/report-html` and the lcov report on `tmp/coverage/report-lcov`.

If I execute `karma start` it generates the same thing. So far so good.

Now suppose I run `karma start` and I remove `tmp/coverage` (to see if it is generating in the wrong directory or duplicate). If I touch a file that is being watched, it generates a html report on `tmp/coverage/report-html`, a lcov report on `tmp/coverage/report-lcov` and another html report on `coverage/PhantomJS 1.9.8 (Linux 0.0.0)`.

**Comment by mmacedo** [comment]
How dumb of me, I had a forgotten terminal still watching it with an old configuration. Sorry about this, I wish I could delete it...

**Comment by Dignifiedquire** [comment]
no worries, happy to hear it was resolved that easily :)
