### ISSUE TITLE
Latest release tag at 0.3.0?

### ISSUE THREAD

**Issue by abhijeetkpawar** [karma-runner/karma-coverage#170]
Any reason for tagging latest release with v0.3.0 ?

**Comment by Dignifiedquire** [comment]
Not sure where you are getting this:

```bash
❯ npm view karma-coverage@latest version
0.4.2
```

and on https://www.npmjs.com/package/karma-coverage the latest is shown as `0.4.2` as well

**Comment by abhijeetkpawar** [comment]
https://github.com/karma-runner/karma-coverage/releases
Here it shows the green tag of "Latest" in front of v0.3.0

**Comment by Dignifiedquire** [comment]
Removed, we are not using github releases at the moment
