### ISSUE TITLE
source html files location in the 0.5.0

### ISSUE THREAD

**Issue by fbengrid** [karma-runner/karma-coverage#172]
Hiya,

Going from 0.4.2 to 0.5.0, all the generated html files get placed in the same folder as their corresponding JS source file and no longer in the coverageReporter.dir path.

If I revert on my local karma-coverage plugin the changes in https://github.com/karma-runner/karma-coverage/commit/d4b2dcf6572251f7fa9db4ec3164398012a377a9 , all the html files are then placed back correctly in the coverageReporter.dir path.

Do we have to change something in our karma conf to recover the previous behavior with karma-coverage 0.5.0 ?

**Comment by Dignifiedquire** [comment]
There was a fix regarding the paths, so maybe something is not picking up correctly. Do you have a small repro, so I can take a look?

**Comment by fbengrid** [comment]
hiya,

Sorry for the late reply, but i was busy with a lot of things, and switching back to version 0.4.2 was working in the mean time.

I took some time today to clone your project locally and launched its tests. A couple of them failed due to the path / and \ not conforming to the expectations... (output: https://gist.github.com/fbengrid/a129e85921c91f250eae)
While this probably wouldn't change much I was surprised to not see some tests launching istanbul on some dummy js file and checking for the existence of the corresponding html files.
Or did i miss those tests (coffescript kind of put me off when i opened the test specs) ?

Anyway it seems I am not the only one having the issue in view of the following threads: https://github.com/karma-runner/karma-coverage/issues/65 and https://github.com/karma-runner/karma-coverage/issues/14

Unfortunately, I can't push the project I'm working on now (not ready yet), but should you update this project with a test doing an actual coverage, I'll happily run it on my system if you need.

my environment:
Node 0.12.6
OS: windows vista & 7

**Comment by goneale** [comment]
I concur this is an issue, sorry I don't have a sample project.

**Comment by fbengrid** [comment]
Closed as the issue present with 0.5.0 is now resolved in 0.5.1.
