### ISSUE TITLE
Karma coverage report files output location

### ISSUE THREAD

**Issue by Gopikrishna19** [karma-runner/karma-coverage#173]
My application structure is:

    /
    --app/src/
             --test.js
             --test..spec.js
    --karma.conf.js
    --other files [package.json, node_modules ...]

When I run `karma start` the coverage files are created under `/output/coverage/PhantomJS/lcov-report/...`

The problem I am facing is the the report files for coverage is generated in the `app/src/` folder instead of `lcov-report` folder. This disallows me to view the coverage results as the `index.html` and `test.js.html` files that show the report are not in `lcov-report` folder. That is:

    /
    --app/src/
             --index.html  <--- wrong location
             --test.js
             --test.js.html  <--- wrong location
             --test.spec.js
    --output/coverage/phantomjs/
             --lcov-report/
                 --  ..      <--- should be here for the report to be accessed
                 --[coverage files]

The following is my `karma.conf.js`:

    module.exports = function (config) {
      'use strict';
    
      config.set({
        basePath: '',
        frameworks: ['mocha', 'sinon-chai'],
        files: [
          'app/js/src/**/*.js',
          'app/js/src/**/*.spec.js'
        ],
        exclude: [],
        preprocessors: {
          'app/js/src/**/!(*.spec).js': ['coverage']
        },
        coverageReporter: {
          type: 'lcov',
          dir: './output/coverage/'
        },
        reporters: ['mocha', 'coverage'],
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        browsers: ['PhantomJS2'],
        singleRun: true
      });
    };

**Comment by Gopikrishna19** [comment]
**update**: 
 1. It seems to work if I am trying to access the html files from lcov report like a normal file form the explorer.
 2. Output-ing reports in src files directory is annoying, don't know how to fix this, may be I'm missing something thats been updated lately.
 3. Downgrading to 0.2.7 worked like charm, which I know it would, because that's the last version I experimented coverage on.

**Comment by ariovistus** [comment]
ditto from windows 7

**Comment by nabinca** [comment]
Seems to be a problem with latest version 0.5.0.
I tested additionally with version 0.3.1 and 0.4.2 and they also create the files in correct folder, only 0.5.0 muddles the files up.

**Comment by jzalucki** [comment]
It won't work only on Windows. Previously karma-coverage plugin was removing baseDir from path so it could be used as relative one and extend your output directory but now it uses absolute path so when you resolve it, it will point to your source folder. 

Why it works under unix?
Location should be calculated properly in "getTreeSummary" of istanbul package using "findCommonArrayPrefix" method. So even if there is absolute path it should output relative one based on common prefix of all files.  Unfortunately all paths are normalized and uses "/", but istanbul takes path.sep which is set to "\" on Windows.

**Comment by Dignifiedquire** [comment]
Can you please recheck with `0.5.1`

**Comment by deltaidea** [comment]
:+1: Windows 10, can confirm that this is fixed in 0.5.1. Thanks!

**Comment by Gopikrishna19** [comment]
update Aug 29, 2015: verified working with v0.5.1, thanks for fixing it
