### ISSUE TITLE
Karma coverage for webcomponents

### ISSUE THREAD

**Issue by rcosnita** [karma-runner/karma-coverage#174]
Hi,

Is there any way I can make karma-coverage generate reports for webcomponents (polymer)?

Kind regards,
Radu

**Comment by Dignifiedquire** [comment]
Well did you try just using it?

**Comment by rcosnita** [comment]
Hi,

I tried using it and found a workaround. If I keep component javascript code into a separate js file rather than webcomponent html file it works.

It would be awesome to support js coverage embeded in html files. I guess a lot of developers will embed web components js code directly into html file.

**Comment by rcosnita** [comment]
<dom-module id="element-name">
  <template>
    <div>{{greeting}}</div>
  </template>

  <script>
    Polymer({
      is: "element-name",

      properties: {
        greeting: {
          type: String,
          value: "Hello!"
        }
      }
    });
  </script>
</dom-module>

It would be nice to have script code included in coverage report.
