### ISSUE TITLE
CoffeeScript coverage preprocessor doesn't change file extension to `.js`

### ISSUE THREAD

**Issue by les2** [karma-runner/karma-coverage#177]
I'm following [this example](https://github.com/karma-runner/karma-coverage/tree/master/examples/coffee) .

The behavior causes problems when using `requirejs`, which will automatically add a `.js` extension to resources it requests.

Here is an [example that demonstrates the problem](https://github.com/les2/karma-coverage/tree/requirejs-coffee-coverage/examples/coffee-requirejs) (which is based off the coffee example in this repo).

See this commit message for more details: https://github.com/les2/karma-coverage/commit/b8839d6c8123b8987f067d12271aaf7df9281da9

This example can serve as documentation for others if we get it working / implement a fix.

**Comment by les2** [comment]
Updated description with link to example demonstrating the problem.

**Comment by les2** [comment]
Thanks for labeling @Dignifiedquire .

Let me know if I can help in any way (e.g., providing debug logs).

**Comment by kmdavis** [comment]
+1

Also @les2 there is a rather old and out of date fork [davidosomething/karma-coverage](https://github.com/davidosomething/karma-coverage) that works for me using coffeescript and requirejs

**Comment by les2** [comment]
> Also @les2 there is a rather old and out of date fork davidosomething/karma-coverage that works for me using coffeescript and requirejs

@kmdavis Took a look and it seems like the code around this line needs to be ported to this karma (not positive, but hopeful). I hope to get a PR together with this change incorporated before long. Thanks for pointing this out!
