### ISSUE TITLE
absolute paths in windows are not correct.

### ISSUE THREAD

**Issue by tswaters** [karma-runner/karma-coverage#178]
27e0b09 fixed up karma-coverage to generate json files with absolute paths which is definitely a step in the right direction, but the paths are incorrect in windows -- they are coming back with slashes, e.g. `C:/something/whatever` 

I've looked into it a bit and these paths are coming right from karma. I'm not entirely sure why karma is transforming windows paths to use `/`, but imagine there is likely a good reason for it.

These paths are inconsistent with the outputs from istanbul... The end result is in a generated report combining all json files, all files use a fully absolute path. If path separators are consistent between json files, all files are relative to a common base, and it looks much nicer.

It's not too hard to fix -- simply pass `file.originalPath` through `require.resolve` and it will turn slashes back into backslashes and everything looks much nicer.

**Comment by Dignifiedquire** [comment]
Should be fixed in `0.5.1`
