### ISSUE TITLE
karma-coverage report includes source mapped file

### ISSUE THREAD

**Issue by robinsving** [karma-runner/karma-coverage#188]
I am trying to get [https://www.npmjs.com/package/browserify-istanbul] to handle the source-mapping of my bundled js-file, and have som far made it work mostly as intended. My problem is that when karma-coverage reports this, and correctly separated the bundle into its source files the reporter still adds the bundled file into the list of files.

In my karma config
```
        files: [
            'dist_test/js/test_bundle.js', // my bundled code
            'dist_test/unit/**/*.js' // my test files
        ],

        plugins: [
            'karma-jasmine',
            'karma-phantomjs-launcher',
            'karma-coverage'
        ],

        preprocessors: {
            'dist_test/js/test_bundle.js': ['coverage']
        },

        coverageReporter: {
            dir: 'dist_test/coverage/',
            subdir: '.',
            reporters: [{
                type: 'text',
            }, {
                type: 'text-summary',
            }, {
                type: 'html',
                subdir: 'html'
            }]
        }
```

In my grunt file:
```
        browserify: {
            "test": {
                dest: "dist_test/js/test_bundle.js",
                src: ["app/app.js", "node_modules/angular-mocks/angular-mocks.js"],
                options: {
                    exclude: ["src/**/*.spec.js"],
                    debug: true,
                    transform: [
                        [require("browserify-istanbul")]
                    ]
                }
            }
```

My resulting coverage report (in html):
![capture](https://cloud.githubusercontent.com/assets/3072502/10339564/51e9d34a-6d0c-11e5-8e11-f98fab69c37d.JPG)

**Expected result:** the files are mapped, but the original file (inside folder ./dist_test/js) is removed as the information contained is not required anymore.

Perhaps I have just missed something simple, but I cannot get this to work.

**Comment by pardoman** [comment]
Did you ever figure out how to have the coverage report use source map files?

**Comment by robinsving** [comment]
@pardoman Since the issue was created I have change to using Webpack instead of browserify.
I have gotten the coverage report to work there as well, and there I managed to get the bundled file to be obfuscated as wished.
Thanks for reminding me. I will close this issue (even if the issue would remain for those sticking with Browserify)

**Comment by pardoman** [comment]
Cool, thanks for the reply.
