### ISSUE TITLE
Karma coverage fails to show correct results

### ISSUE THREAD

**Issue by jotaoncode** [karma-runner/karma-coverage#190]
I need some help regarding Karma with browserify coverage. I created a repo with the test I am running in here:

https://github.com/jotaoncode/web-istanbul

The results on my coverage are the following: ![Results of coverage] (http://i.stack.imgur.com/66FtD.png)

**The test only runs over the function index. But as you can see the results are a 100% and marks only the first row of the file with a green color.**

I have seen cases where istanbul shows correctly the coverage values, I have changed the test and the source but nothing.

I also have this karma configuration:

```javascript
module.exports = function(config) {
  config.set({
    //logLevel: 'LOG_DEBUG',

    reporters: ['spec', 'coverage'],

    // Continuous Integration mode
    // if true, Karma captures browsers, runs the tests and exits
    singleRun : true,

    autoWatch : false,

    // base path that will be used to resolve all patterns (eg. files, exclude)
    basePath: '',

    port: 9876,

    // frameworks to use
    // available frameworks: https://npmjs.org/browse/keyword/karma-adapter
    frameworks: [
      'mocha',
      'browserify'
    ],

    files: [
      'src/**/*.js',
      'test/*.js'
    ],

    // list of files to exclude
    exclude: [],

    preprocessors: {
      'src/**/*.js': ['browserify', 'coverage'],
      'test/**/*.js': ['browserify']

    },

    coverageReporter: {
      reporters: [
        { type: 'html' },
        { type: 'text' },
        { type: 'lcovonly' }
      ],
      instrumenterOptions: {
        istanbul: {
          noCompact: true
        }
      },
      instrumenter: {
        'test/**/*.js': 'istanbul'
      },
      includeAllSources: true
    },


    // enable / disable colors in the output (reporters and logs)
    colors: true,

    // start these browsers
    // available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
    browsers: [
      'PhantomJS2'
    ]

  });
};
```
**If you ran the tests you will see that it actually works fine, but the coverage report is not correct.**

I also created this ticket http://stackoverflow.com/questions/33422910/karma-coverage-fails-to-show-correct-results

Thank you very much for your help.

**Comment by jotaoncode** [comment]
After doing some research I used this package to make a transformation for istanbul with browserify:

https://github.com/devongovett/browserify-istanbul

Now it is working as expected: 

![](http://i.stack.imgur.com/Uqfs3.png)

**Comment by fullstackpug** [comment]
Would you mind share how exactly you use browserify-istanbul to fix the problem, I think I have the same problem too.

**Comment by jotaoncode** [comment]
@fullstackpug it is being a while since the last time I worked on this, you can find working solution here:
https://github.com/jotaoncode/web-istanbul-browserify
Hope it helps
