### ISSUE TITLE
The coverage-final.json file is not generated when I use multiple reporters

### ISSUE THREAD

**Issue by remojansen** [karma-runner/karma-coverage#198]
If I use:

```
reporters: [
  {type: 'json', dir: 'coverage'}
]
```

The `coverage-final.json` file is generated fine, but if I use:

```
reporters: [
  {type: 'html', dir: 'coverage'},
  {type: 'json', dir: 'coverage'}
]
```

The html reports are generated but the `coverage-final.json` is not generated anymore.

**Comment by tsauerwein** [comment]
Try with:

    coverageReporter: {
      dir : 'coverage/',
      reporters: [
        {type: 'html', subdir: 'report-html'},
        {type: 'json', subdir: './', file: 'coverage.json'}
      ]
    }

This puts the html report in 'coverage/report-html' and the json file is at ''coverage/coverage.json'.
