### ISSUE TITLE
As in right now, is it possible to generate ES2015 coverage using babel6 + karma-coverage?

### ISSUE THREAD

**Issue by fernandofleury** [karma-runner/karma-coverage#202]
I've been trying for a little while right now (with no success) to generate proper coverage of my ES2015 code, which is transpiled by babel6.

Is it possible to generate it using the original karma-coverage project (not forks)?

**Comment by Francisc** [comment]
Opened January 7th and still no comments... lovely.

**Comment by fernandofleury** [comment]
I've managed to make it work with a few tweaks @Francisc do you need some help?

**Comment by Francisc** [comment]
I've done it as well, order of processors did it for me.
Was just disappointed to see the lack of involvement when it comes to ES2015.

**Comment by ronichoudhury** [comment]
@fernandofleury @Francisc I'm curious how you went about this. I've got it working as well but I'm using [babel-istanbul](https://github.com/ambitioninc/babel-istanbul) to do it.

**Comment by hoisel** [comment]
Hi @fernandofleury @Francisc @ronichoudhury 
I've got it working with these following steps:
https://github.com/gunnarlium/babel-jspm-karma-jasmine-istanbul

**Comment by topheman** [comment]
I managed to get code coverage reports on ES6+ source code on this project [topheman/react-es6-redux](https://github.com/topheman/react-es6-redux), using the babel plugin [babel-plugin-\_\_coverage\_\_](https://github.com/dtinth/babel-plugin-__coverage__).

I wrote a blog post about that: **[ES6+ code coverage with Babel plugin](http://dev.topheman.com/es6-code-coverage-with-babel-plugin/)**

Here is the [release](https://github.com/topheman/react-es6-redux/releases/tag/v3.1.0) (v3.1.0) where you'll find;

* implementation of the es6+ coverage with karma-coverage + babel-plugin-\_\_coverage\_\_
* support for [coverralls.io](https://coveralls.io/github/topheman/react-es6-redux?branch=master) (if you're interested)

**Comment by jas-chen** [comment]
Here is my solution for this issue: [karma-sourcemap-writer](https://github.com/jas-chen/karma-sourcemap-writer).
