### ISSUE TITLE
Adding a 'checkCoverage' option to compare coverage with a defined threshold

### ISSUE THREAD

**Issue by sebarmeli** [karma-runner/karma-coverage#21]
At the moment it's not possible to run the 'check-coverage' command available in Istanbul. It would be cool to have a way of specifying thresholds for statement coverage, function coverage and branch coverage.

I was thinking something like 

```
checkCoverage: {
   statement : 90,
   branch: 80,
   function: 100
}
```

to be added to the Karma conf file.

Thoughts?

**Comment by peter-mouland** [comment]
thanks for the interest, i've done it quite crudely with gulp tasks. unfortunately i dont have the time to go through the coverage plug and see how to do it properly. hopefully one day....
```
    gulp.task('test:single-run', function (done) {
        karma.start({
            configFile: findup(paths.test.config),//path to  karma.conf.js
            singleRun: true
        }, done);
    });
    gulp.task('test', ['test:single-run'], function(cb){
        var results = require(findup(paths.test.summary)); //path to the summay.json set in karma.conf.js
        var config = require(findup(paths.test.config));//path to  karma.conf.js
        var coverage = config({set: function(conf){return conf;}}).coverageReporter;
        var thresholds = coverage.reporters[0].watermarks; //path to watermarks within for type: html
        var err = false;
        for (var file in results){
            for (var threshold in thresholds){
                if (results[file][threshold].pct < thresholds[threshold][0]){
                    handleError(file + ' : ' + threshold + ' Coverage is too low (<' + thresholds[threshold][0] + '%)');
                    err = true;
                }
            }
        }
        if (err) process.exit(1); //exit once all errors have been gathered
        cb();
    });
```

**Comment by andrew-cunliffe** [comment]
The watermarks are just settings for the report output colour breakpoints it seems (which is nice to see how to control this), the request looks more like a way to send information to istanbul check-coverage

```
check-coverage
          checks overall coverage against thresholds from coverage JSON
          files. Exits 1 if thresholds are not met, 0 otherwise
```

This would be very useful I use istanbul with mocha on backend node.js projects with check-coverage there is almost essential.

At the moment it appears looking at the code only the report option is being implemented, so implementation of check-coverage would be great

:+1:

**Comment by stramel** [comment]
@andrew-cunliffe @peter-mouland I think just installing `istanbul` and requiring `child_process`'s `spawn` should result in an easy implementation for now.

```js
// untested
var spawn = require('child_process');

gulp.task('coverage:check', function () {
var child = spawn('istanbul', [
  '--statements=100',
  '--functions=100',
  '--branches=100',
  '--lines=100'
], {cwd: process.cwd()});

child.on('close', function (errorCode) {
  // Handle Error
});
```

**Comment by nmalaguti** [comment]
I'm working on a PR for this issue. The implementation mostly comes from https://github.com/gotwarlost/istanbul/blob/master/lib/command/check-coverage.js and is based on the istanbul configuration file.

It will cause the build to fail by modifying the `results.exitCode` value if the coverage checks fail.

Info from the README:

#### check
**Type:** Object

**Description:** This will be used to configure minimum threshold enforcement for coverage results. If the thresholds are not met, karma will return failure. Thresholds, when specified as a positive number are taken to be the minimum percentage required. When a threshold is specified as a negative number it represents the maximum number of uncovered entities allowed.

For example, `statements: 90` implies minimum statement coverage is 90%. `statements: -10` implies that no more than 10 uncovered statements are allowed.

`global` applies to all files together and `each` on a per-file basis. A list of files or patterns can be excluded from enforcement via the `exclude` property. On a per-file or pattern basis, per-file thresholds can be overridden via the `overrides` property.

```javascript
coverageReporter: {
  check: {
    global: {
      statements: 50,
      branches: 50,
      functions: 50,
      lines: 50,
      excludes: [
        'foo/bar/**/*.js'
      ]
    },
    each: {
      statements: 50,
      branches: 50,
      functions: 50,
      lines: 50,
      excludes: [
        'other/directory/**/*.js'
      ],
      overrides: {
        'baz/component/**/*.js': {
          statements: 98
        }
      }
    }
  }
}
```

**Comment by ashwinr** [comment]
ping :) can someone look at PR https://github.com/karma-runner/karma-coverage/pull/141 please?
