### ISSUE TITLE
README basic configuration example doesn't work. missing plugin karma-coverage

### ISSUE THREAD

**Issue by bcowgill** [karma-runner/karma-coverage#224]
I had to add

plugins: ['karma-coverage']

to the existing plugins to get it to work.

please update the docs.

**Comment by dignifiedquire** [comment]
Please refer to http://karma-runner.github.io/0.13/config/plugins.html for details on how plugin loading works. There is no need in the default use case to add a `plugins` section to your karma.conf

**Comment by bcowgill** [comment]
I have looked at that page and I have karma-coverage installed locally but without a plugin configuration line karma will not run coverage. So despite what the documentation says, it is not working for me.

> enzyme-example-karma-webpack@0.1.4 test 
> ./node_modules/karma/bin/karma start --single-run --browsers PhantomJS --debug

18 04 2016 10:00:09.998:WARN [preprocess]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?
18 04 2016 10:00:10.011:WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?

 (master * u=)$ ls node_modules/ | grep karma
karma
karma-babel-preprocessor
karma-browserify
karma-chrome-launcher
karma-coverage
karma-jasmine
karma-mocha
karma-phantomjs-launcher
karma-sourcemap-loader
karma-webpack

karma.conf.js
    plugins: [
      //'karma-coverage',  // uncomment this and it works.
      'karma-webpack',
      'karma-jasmine',
      'karma-sourcemap-loader',
      'karma-chrome-launcher',
      'karma-phantomjs-launcher'
    ],

**Comment by dignifiedquire** [comment]
You have to remove the whole `plugins` section from your karma-conf it's not needed

**Comment by bcowgill** [comment]
Thanks, that does the trick. It wasn't exactly clear from the documentation that plugins is deprecated or optional.

**Comment by JimLynchCodes** [comment]
@dignifiedquire Terrible suggestion to remove the whole plugins folder and did not even work for me.

I am spent days trying to get coverage to find my files, but it always says 0/0. Why is this so difficult and no up-to-date documentation?? 🤔
