### ISSUE TITLE
karma-coverage does not collect information with karma 1.x with autoWatch=true

### ISSUE THREAD

**Issue by weblogixx** [karma-runner/karma-coverage#236]
Hi all,

I am currently running into problems after updating karma from 0.13 to 1.x. With karma@1.1, coverage information is collected without problems in single runs, but the output is wrong when autoWatch is set to true. You may check this by cloning the following repository (https://github.com/weblogixx/react-webpack-template/tree/2.x). After installation, just compare the output of ```npm test``` and ``` npm run test:watch```.  This behaviour does not happen with karma@0.13.x.

**Comment by mspoulsen** [comment]
Same issue here. I downgraded to karma 0.13.22 and it worked fine.

**Comment by owieboy** [comment]
I am having the same issue. Karma-coverage is always showing 100% coverage when `autoWatch` is used

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
----------|----------|----------|----------|----------|----------------|
All files |      100 |      100 |      100 |      100 |                |
----------|----------|----------|----------|----------|----------------|

Coverage metrics is correct when `singleRun` option is used though.

**Comment by weblogixx** [comment]
Info: After updating karma to the latest stable (1.1.1), after that, the problem went away. Seems to be only happening with karma@1.1.0...

**Comment by dignifiedquire** [comment]
this was due to a bug which was fixed in the latest karma release
