### ISSUE TITLE
karma-coverage doesn't work with nocache=true option 

### ISSUE THREAD

**Issue by said-abidi** [karma-runner/karma-coverage#237]
I used the option nocache=true in the karma conf file. 
Since then, the coverage reported is 100% but no file are watched.
I suspect that the coverage doesn't work if the file is not loaded in the cache of the browser. 
Can someone confirm? Is there any workaround?

**Comment by azaslavsky** [comment]
I just ran into this problem myself.  If you set your `logLevel` config to `config.LOG_DEBUG` in your karma.conf.js, you should see a warning along the lines of:

```
DEBUG [watcher]: Not preprocessing "%s" due to nocache
```

It seems that the coverage preprocessor is not activated on nocached files, probably for performance reasons.
