### ISSUE TITLE
Update to the new Istanbul API

### ISSUE THREAD

**Issue by dpogue** [karma-runner/karma-coverage#245]
http://istanbul.js.org/

This should provide much better sourcemap support, and resolve long-standing issues with testing Babel/ES6 and TypeScript projects.

**Comment by caiogondim** [comment]
I managed to get coverage working in ES2015+ with [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul)

**Comment by dpogue** [comment]
This is resolved with karma-coverage 2.0.0 🎉
