### ISSUE TITLE
Async await support

### ISSUE THREAD

**Issue by furstenheim** [karma-runner/karma-coverage#321]
Karma coverage is not able to parse files that contain async/await I get a parsing error:

ERROR [preprocessor.coverage]: Line 15: Unexpected token function

Thanks

**Comment by furstenheim** [comment]
As a workaround one can use https://github.com/istanbuljs/babel-plugin-istanbul for instrumenting the code and karma-coverage to make the coverage

**Comment by lucianolucianoluciano** [comment]
up

**Comment by lucianolucianoluciano** [comment]
@furstenheim Could you explain how you configured this plugin?

**Comment by furstenheim** [comment]
@lucianolucianoluciano you can take a look at the [karma conf](https://github.com/furstenheim/automatic-scatter-labelling/blob/master/karma.conf.js) of the project. It is actually quite simple. As a babel plugin you add istanbul and that will add the information for the coverageReporter. Don't forget to run

    npm install --save babel-plugin-instanbul

**Comment by GammaNu** [comment]
Are you planning to add async/await native support in karma-coverage ?

I use them in my project without babel conversion, so it could be helpfull !

until then, il will drop karma-coverage and cross test with jest instead for coverage.

**Comment by johnjbarton** [comment]
To update the language support, istanbul needs to be updated to pull esprima 4.x.

**Comment by kierans** [comment]
It maybe that Istanbul will not update the esprima version because `istanbul` has been [deprecated in favour of ](https://github.com/gotwarlost/istanbul/issues/733#issuecomment-310846820) `istanbuljs` (which does support async/await).

**Comment by anthony-redFox** [comment]
should be done in version 2.X, fill free to reopen if still have a error
