### ISSUE TITLE
Unable to get a reliable coverage report

### ISSUE THREAD

**Issue by robcornelius** [karma-runner/karma-coverage#354]
Every single thing I have tried with karma-coverage has failed in one way or another. I either get 0%/0 coverage on the correct list of files or 100%/0 on no files at all.

I have tried karma-coverage-allsources to try and fix the issues with no files being tested. I have tried various report generators and I have downgraded karma-coverage to 0.2.6.

Absolutely nothing works reliably. 

If no one wants to maintain this project then it should be deleted

**Comment by johnjbarton** [comment]
I guess you will just have to dig in an debug your configuration. One suggestion I've found helpful is to add a `console.log('config', config); ` right after the config is read for use:
https://github.com/karma-runner/karma/blob/master/lib/server.js#L83

That way you can check for config overwrites.
