### ISSUE TITLE
Coverage break tests with newline backslashes

### ISSUE THREAD

**Issue by ddimitrop** [karma-runner/karma-coverage#355]
I have seen that there is problem with code like

return `\
hi';

which will be instrumented to

return;
<some code coverage code>
`\
hi';

Example:

`describe('karam coverage', () => {
  function hi() {
    return '\
hi';
  }

  it('should work with newline backslash - it is supported on browsers', () => {
    expect(hi()).toBe('hi');
  });
});`

This will pass for karma test but fail for karma coverage.

I believe that this is an issue in some dependency and I am wondering if you could help me locate that to report this there.

**Comment by johnjbarton** [comment]
My guess would be escodegen, the component used by istanbul used by karma-coverage, to emit code instrumented for coverage from the syntax tree created by esprima. If the esprima parse failed, the result would be an error in parsing, however it is possible that esprima creates the wrong tree and escodegen is then not to blame.

Those tools have cool on-line demo pages you can use to experiment with your code. Please let us know what you find. Maybe try http://esprima.org/demo/rewrite.html

**Comment by johnjbarton** [comment]
This is fixed in esprima but not released. https://github.com/jquery/esprima/issues/1928
