### ISSUE TITLE
Karma 2.x.x issues

### ISSUE THREAD

**Issue by dalefrancis88** [karma-runner/karma-coverage#362]
Is there any intention to have this upgraded to work with Karma 2? Currently when i upgrade to 2.0 there no longer returns any results, when i am in karma 1.x it returns the expected results

**Comment by johnjbarton** [comment]
Please upgrade to karma 3.0 (the current version) and run with log-level DEBUG. Post the result.

I don't expect any work related to karma 2.x, 3.x is current.
