### ISSUE TITLE
Shouldn't this library become deprecated?

### ISSUE THREAD

**Issue by nadavye** [karma-runner/karma-coverage#364]
Hi,

Since this library is intended to be used for a two years old a deprecated version of Istanbul, I wonder if there's a point in maintaining this library as it just confuses end users?

Deprecated version of Istanbul: https://github.com/gotwarlost/istanbul
Latest version of Istanbul: https://github.com/istanbuljs

Thoughts?

Nadav

**Comment by johnjbarton** [comment]
I think you could have more impact with pull requests.
