### ISSUE TITLE
Is there a plan to update istanbul

### ISSUE THREAD

**Issue by mobilutz** [karma-runner/karma-coverage#368]
Because of a recent NPM security advisory https://www.npmjs.com/advisories/755 , I stumbled over the Deprecation of `istanbul`:
https://github.com/gotwarlost/istanbul#istanbul---a-js-code-coverage-tool-written-in-js

Is there a plan to switch to `nyc` because istanbul has been deprecated for almost 2 years now?

**Comment by johnjbarton** [comment]
Please post a plan or a PR starting action on such a plan.
