### ISSUE TITLE
No coverage report created

### ISSUE THREAD

**Issue by abbr** [karma-runner/karma-coverage#395]
Recently I upgraded karma-coverage from 0.5.3 to 2.0.1 for a 2-year old react project along with other build modules such as webpack, karma, mocha, etc. The project had a *coverage* folder. After deleting the folder and re-run karma start, neither the *coverage* folder nor coverage reports are created. Other test tasks completed successfully

Here is my karma.conf.js 

```
if (process.argv.indexOf('--browsers') < 0) {
  process.env.CHROME_BIN = require('puppeteer').executablePath()
}

const webpackCfg = require('./webpack.config')
module.exports = function(config) {
  let reporters = ['mocha', 'coverage']
  // don't run coverage in watch (CI) mode
  if (config.autoWatch && !config.singleRun) {
    reporters = ['mocha']
  }
  config.set({
    browsers: ['ChromeHeadless'],
    files: ['test/loadTests.js'],
    captureTimeout: 60000,
    frameworks: ['mocha', 'chai'],
    client: {
      mocha: {}
    },
    colors: true,
    singleRun: true,
    logLevel: config.LOG_INFO,
    'reporters': reporters,
    preprocessors: {
      'test/loadTests.js': ['webpack', 'sourcemap'],
      'src/**/*.js': ['coverage']
    },
    webpack: webpackCfg,
    coverageReporter: {
      type: 'html',
      dir: 'coverage/'
    }
  })
}
```

**Comment by johnjbarton** [comment]
Try running with logLevel config.LOG_DEBUG to see if you get any hints from that.

**Comment by abbr** [comment]
Nothing abnormal as I could tell. karma-coverage is loaded
```
...
02 12 2019 16:50:47.489:DEBUG [plugin]: Loading plugin C:\Users\x\myProj\node_modules/karma-coverage.
...
```

**Comment by johnjbarton** [comment]
Do you see lines like "Processing..." from 
https://github.com/karma-runner/karma-coverage/blob/master/lib/preprocessor.js#L111

**Comment by abbr** [comment]
No. Do you know of any working examples/projects support latest version of react, webpack, karma, mocha and karma-coverage?

**Comment by abbr** [comment]
Turns out the cmd I used to invoke test, `karma start`, sets `--auto-watch` and `--no-single-run`  by default. In my `karma.conf.js`, `reporters` exclude `coverage` when in watch (CI) mode.
