### ISSUE TITLE
v2.0.2 lcov.info absolute paths now incorrectly translated to relative paths

### ISSUE THREAD

**Issue by tande35006** [karma-runner/karma-coverage#415]
Updated from karma-coverage 2.0.1 to 2.0.2 and the paths in the lcov.info are now being translated to relative paths.  Using sonarcloud.io for coverage analysis which doesn't support the relative paths.

v2.0.1 lcov.info file:
![image](https://user-images.githubusercontent.com/38557781/80380505-95a0bd00-8897-11ea-95fb-129e44b55252.png)

v2.0.2 lcov.info file now produces:

![image](https://user-images.githubusercontent.com/38557781/80380604-b2d58b80-8897-11ea-94ad-d12410af4d4e.png)

sonarcloud log:
![image](https://user-images.githubusercontent.com/38557781/80380999-2f686a00-8898-11ea-804b-8bf9cdbbba78.png)

**Comment by anthony-redFox** [comment]
@tande35006  try to use relativePath: false for lcov report

**Comment by gingemonster** [comment]
anyone got this working, not 100% sure where the "relativePath: false" flag should be set? I assume in karma.config.js so I tried a few places and none seem to work. Where should it go?

`    coverageReporter: {
      reporters: [ 
        { type: 'html' },
        { type: 'lcovonly', file: '../../../../lcov.info' },
        { type: 'text-summary' },
        { type: 'teamcity' }
      ],
      dir: path.resolve(__dirname, 'coverage-karma'),
      subdir: '.',
    },`

**Comment by anthony-redFox** [comment]
sorry, it is my mistake. it is issue https://github.com/istanbuljs/istanbuljs/issues/529

you can define projectRoot for project and should be resolved

**Comment by moussetc** [comment]
@anthony-redFox 
> sorry, it is my mistake. it is issue [istanbuljs/istanbuljs#529](https://github.com/istanbuljs/istanbuljs/issues/529)
> 
> you can define projectRoot for project and should be resolved

Hi, I'm struggling with this issue and I don't see how to define this `projectRoot` option with Karma. Could you provide a karma.conf example that generates absolute path with karma-coverage >= 2.0.2?
