### ISSUE TITLE
(question) how ignore coverage from bundle app

### ISSUE THREAD

**Issue by miniben-90** [karma-runner/karma-coverage#422]
Hello

I've a question with the coverage and bundled dependencies with App. Wee are using karma-coverage (Karma and Jasmine) to make some tests for on our Aurelia Project.

The project and some dependencies are bundled on the same file. So when I run the test I have "node_modules folder" include in the coverage. I tried to use exclude parameter, but nothing change. I also tried to add check->each->overrides configuration on coverageReporter to fake the statements but not a big success too.

So my question:
Is there a way to exclude, ignore or to fake the statements from karma setup when the dependencies are bundled with the app?

Best regards.

**Comment by johnjbarton** [comment]
As far as I know, the coverage works by instrumenting the files listed in the config. If you list a bundled file, then that file will be instrumented. The `exclude` parameter works on files and directories not on bundles.

You may get more insight by running with `--logLevel=debug`
