### ISSUE TITLE
Lcov file paths changed from absolute to relative

### ISSUE THREAD

**Issue by veke** [karma-runner/karma-coverage#452]
Due to changed file paths in lcov file after v2.0.1 is breaking SonarQube integration for typescript coverage. 

Change introduced in v2.0.2 and is now backwards incompatible.

**Comment by veke** [comment]
https://github.com/istanbuljs/istanbuljs/issues/529#issuecomment-664416261

**Comment by veke** [comment]
Updated Sonarqube version. Now understands relative paths.

**Comment by swendlandt** [comment]
Hello @veke, which SonarQube version did you need to update to to fix the issue?

We were running into the same issue when updating karma-coverage with SonarQube Version 9.9.2 (build 77730).
