### ISSUE TITLE
NPM not available: karma-coverage@2.1.1

### ISSUE THREAD

**Issue by DmitriyIvanko** [karma-runner/karma-coverage#466]
npm ERR! notarget No matching version found for karma-coverage@2.1.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by anthony-redFox** [comment]
Hello, check that you don't have .npmrc file, it could block updates. I checked that is available to download new version from npm .

**Comment by DmitriyIvanko** [comment]
Thanks!
