### ISSUE TITLE
 Getting [Error: EEXIST: file already exists, mkdir  errors in 2.1.1, not in 2.1.0

### ISSUE THREAD

**Issue by MauriceSchoenmakers** [karma-runner/karma-coverage#467]
i still get on some machines with 2.1.1

09 02 2022 19:05:09.847:ERROR [coverage]: Unexpected error while generating coverage report.
 [Error: EEXIST: file already exists, mkdir '/Users/pbob/jenkins/workspace/Build_o2-myonlife-frontend_Master/o2-myonlife-app/test-output/coverage/Chrome 98.0.4758.80 (Mac OS 10.15.7)'] {
  errno: -17,

even after the latest 2.1.1 fix in commit bca2c69d43332598acb30d8e5d6e26d783bc06fb

with 2.1.0 there are no errors

---

**Comment by jginsburgn** [comment]
@MauriceSchoenmakers can you please share your repro steps?

**Comment by capc0** [comment]
Im also getting this on windows sometimes when starting the test run and the plugin tries to create the coverage directory which already exists.

**Comment by capc0** [comment]
update: this only gets thrown when the coverate directory does **not** exist already. So the first run after manually deleting the `coverage` dir always fails.

**Comment by tuxtor** [comment]
Hi to add a little detail one of my (headless) builds recently broke while enabling lcov reporter with this same error.

I've investigated a little bit further and so far I've found this, here my steps to reproduce:

# Error reproduction:

- I do a `rm -Rf coverage`
- I've enabled html, lconv and text-summary reporters with:

```
reporters: [
        { type: 'html' },
        { type: 'lcov' },
        { type: 'text-summary' }
      ]
```

- After running test with coverage (yarn) , the output is

```
16 02 2022 16:30:22.169:ERROR [coverage]: Unexpected error while generating coverage report.
 [Error: EEXIST: file already exists, mkdir '/home/tuxtor/Nabenik/Menarini/Proyectos/menarini-directory-ng/coverage/menarini-directory-ng'] {
  errno: -17,
  code: 'EEXIST',
  syscall: 'mkdir',
  path: '/home/tuxtor/Nabenik/Menarini/Proyectos/menarini-directory-ng/coverage/menarini-directory-ng'
}
```

If I run it again the output is OK


# No error

- I do a `rm -Rf coverage`
- I've enabled **only lconv and text-summary** reporters with:

```
reporters: [
        { type: 'lcov' },
        { type: 'text-summary' }
      ]
```

- After running test with coverage (yarn), the output is  OK

**Comment by ralphwillgoss** [comment]
I can confirm rolling back to `2.1.0` fixes the issue.
I've done this, to reduce the warning noise in my build pipeline.

**Comment by devoto13** [comment]
Please make sure that you have also updated karma to [6.3.15](https://github.com/karma-runner/karma/releases/tag/v6.3.15) or newer. It contains the related fix to properly handle EEXISTS errors in the helper. I would be interested to see a reproduction if you still get the error after the upgrade.
