### ISSUE TITLE
Make ibrik optional to ease offline installation

### ISSUE THREAD

**Issue by yarray** [karma-runner/karma-coverage#49]
Hi,

Recently I had to develop on a machine without internet access. I managed to install some npm packages offline but got stuck in this one because ibrik tried to fetch content from github. Though I could come out some dirty workarounds to overcome this. It was really frustrating because I had difficulties in downloading something that I don't use (I wrote only plain javascript).

Is it possible to make ibrik optional?

**Comment by maksimr** [comment]
closed by https://github.com/karma-runner/karma-coverage/pull/130
