### ISSUE TITLE
Broken coverage, not covering coffee files

### ISSUE THREAD

**Issue by Fandekasp** [karma-runner/karma-coverage#56]
I'm working on a Meteor project [CoinsManager](https://github.com/CoinsManager/CoinsManager/), with [RTD](http://rtd.xolv.io/) & Karma

As per [rtd/#126](https://github.com/xolvio/rtd/issues/126), After writing unit tests that pass succesfully, my test runner fails at the test coverage checker.

This is strange, because the reports shows 100% tests (only 1 js file covered):

![coverage](http://i.imgur.com/ScdLxTT.png)

Also, if I try to make coffee files visible by coverage in my `karma.conf.js` with:

        preprocessors : {
            '**/app/**/*.js': 'coverage',
            '**/app/**/*.coffee': 'coverage',   # Line added!
            '**/*.coffee': 'coffee'
        },

I get [this traceback](http://sprunge.us/eDUb)

Any idea why the Test coverage checker fails ? And how to properly get my coffee files covered ?

Thank you for your support

**Comment by Dignifiedquire** [comment]
If you want to use coverage on coffee-script you need to use ibrik.
