### ISSUE TITLE
"Can not load "coverage", it is not registered!" error when running

### ISSUE THREAD

**Issue by apond** [karma-runner/karma-coverage#59]
I install karma-coverage like this:
npm install karma-coverage --save-dev

I have a package file that contains this:
"devDependencies": {
    "karma": "0.10.2",
    "karma-coverage": "0.1.5",
    "karma-junit-reporter": "0.1.0",
    "karma-jasmine": "0.1.3",
    "karma-chrome-launcher": "0.1.0",
    "karma-ie-launcher": "0.1.1",
    "karma-safari-launcher": "0.1.1",
    "karma-firefox-launcher": "0.1.0"
  },

And a config file that looks contains this:
    // test results reporter to use
    // possible values: 'dots', 'progress', 'junit', 'growl', 'coverage'
    reporters: ['dots', 'junit', 'coverage'],

```
preprocessors: {
  // source files, that you wanna generate coverage for
  // do not include tests or libraries
  // (these files will be instrumented by Istanbul)
  'jstarget/**/*.js': ['coverage']
},

// configure the coverage reporter
coverageReporter: {
  type : 'html',
  dir : 'coverage/'
},
```

And I get an error that looks like this:
WARN [reporter]: Can not load "coverage", it is not registered!
  Perhaps you are missing some plugin?

What do I need to do?

**Comment by ryoia** [comment]
I am having the same problem currently, it worked fine yesterday, but now it says can not load 'webpack'/'coverage'/'sourcemap' did you forget to install it? i have them in the devDep., and did npm i already. Also having 'Perhaps you are missing some plugin' for those 3 as well.

**Comment by davidpricedev** [comment]
I had this problem as well. I was able to get things working once I deleted all the global karma packages and reinstalled karma-cli as the only global (karma-related) package.

**Comment by ryoia** [comment]
I got it working by doing the same thing, thanks for replying!

**Comment by simon-nguyen** [comment]
@davidpricedev @ryoia I just got the same issue working with webpack, and when I run `karma start`, it said "cannot load webpack, source-map" I did as you suggested and now it works perfectly. Thanks.

**Comment by ryoia** [comment]
awesome @simon-nguyen !

**Comment by eelogic** [comment]
I ran karma with gulp and got the same issue, fixed as @apond mentioned:

**Comment by ekkis** [comment]
I've found that if I declare the `plugins` option with any values, it fails to load all the `karma-*` modules.  if I remove it altogether then it works fine.  I'm not sure why I would ever want to use `plugins` in that case, since I could only be declaring plugins that would be loaded anyway, without the declaration

**Comment by brutalcrozt** [comment]
I still facing that error with out explicitly specify `karma-coverage` as plugins.
as far as i remember i install karma-cli and karma-coverage globally.
IMO , should update the `README.md`

**Comment by dignifiedquire** [comment]
plugins need to be installed locally as devdependencies as stated in the readme then the auto loading works as expected

**Comment by brutalcrozt** [comment]
@dignifiedquire I also install it locally, i just notice that it work after i explicitly specify `karma-coverage` as plugins. Before that still yell coverage not registered.

**Comment by julmot** [comment]
@dignifiedquire I can confirm the behavior of @brutalcrozt.

**Comment by deepakkaithwas** [comment]
I got the same [WARN] because the plugin 'karma-coverage' was not defined inside the plugins of the config, try to see if adding it fixes your warning, not sure if it will fix your full problem.

```
plugins: [
  'karma-jasmine',
  'karma-coverage'
],
```

**Comment by MPV** [comment]
For me, doing any of this doesn't help:
- Adding `plugins` to `karma.conf.js` with all Karma plugins I use.
- Not having `plugins` defined in `karma.conf.js`.

**Comment by jennet** [comment]
I had this problem on the build server (team city) and it turned out to be because I'd installed karma globally, instead of `karma-cli` (which is the only one needed globally on the build server)

I have no plugins defined in config, they are loaded automatically via their naming convention.

[Solution found here](https://github.com/karma-runner/karma/issues/1488#issuecomment-120363831)

**Comment by alandroid** [comment]
I have a similar issue but may be specific to the reporter:
https://github.com/dgarlitt/karma-nyan-reporter/issues/43

**Comment by johnjbarton** [comment]
This error message means the npm module containing the registration entries did not execute. So the module was not `require`-d or it failed during load. Most plugins are `require`-d but listing them in the plugin section of the config.

Using logLevel debug may help:
http://karma-runner.github.io/3.0/intro/troubleshooting.html

**Comment by JimLynchCodes** [comment]
I added 'karma-coverage', but still no files being found... 😥

Coverage reports should cover ALL files by default, and it should be EASY to configure this.

Currently, this is a seriously horrible dev experience, just sayin'.

**Comment by VicTMPDeV** [comment]
I had the same problem and just fix it after added 'karma-coverage' package, and then, in the karma.conf.js file, remove the require of karma-coverage-istanbul-reporter, and finally add the require of the new package, like this: require('karma-coverage')

I hope this will be helpfull.
