### ISSUE TITLE
lcov report built into a folder name that changes per environment

### ISSUE THREAD

**Issue by SimplGy** [karma-runner/karma-coverage#61]
Coverage builds into a directory that includes the name of the browser and the OS. This makes it nondeterministic.

With these options:

    coverageReporter: # https://github.com/karma-runner/karma-coverage
      reporters: [
        {
          type: 'text-summary'
        }
        {
          type: 'lcov'
        }
      ]
      dir: '../.tmp/coverage'

The coverage output goes to:

    .tmp/coverage/PahtomJS 1.9.2 (Mac OS X)/lcov-report

If my dev environment is osx and my CI environment is Unix, the coverage report will be in a different place, making it difficult to automate around. (in my case I want to have the build system put it in a central location so the CI server has a coverage report in a fixed location every build)

Is the changing folder name intentional? Is there a way around this, either by locking down the folder name or by pulling the calculated name out of a variable and passing it to the build system?

**Comment by Dignifiedquire** [comment]
Should be solved. See #62 for more details
