### ISSUE TITLE
Coverage Report Dumps .js.html files into same directory as covered files when karma conf file in separate directory

### ISSUE THREAD

**Issue by opnsrce** [karma-runner/karma-coverage#65]
I've noticed the following possible bug:

When the karma conf file is in a separate directory from the files being tested, the coverage report files don't get placed in the ``coverage`` directory. Instead, the files get placed in the same directory as the files being covered.

Here's my karma conf file for reference:
```javascript
module.exports = function(config) {
    config.set({
        basePath: './',
        autoWatch: true,
        frameworks: ['jasmine'],
        files: [
            '../public_html/libs/jquery/*.js',
            '../public_html/libs/mylib/lib.js',
            '../public_html/libs/mylib/utility.js',
            '../public_html/libs/mylib/config/*.js',
            '../public_html/libs/mylib/enumerations.js',
            '../public_html/libs/mylib/apiComm.js',
            '../public_html/libs/mylib/baseObject.js',
            '../public_html/libs/mylib/book.js',
            '../public_html/libs/mylib/file.js',
            '../public_html/libs/mylib/library.js',
            '../public_html/libs/mylib/publishing.js',
            '../public_html/libs/mylib/topic.js',
            '../test/*Spec.js'
        ],
        reporters: ['progress', 'coverage'],
        preprocessors: {
            '../public_html/libs/mylib/*.js': ['coverage']
        },
        port: 9876,
        colors: true,
        browsers: ['Chrome'],
        captureTimeout: 60000,
        singleRun: false
    });
};
```

**Comment by lukeapage** [comment]
confirmed also, same problem, `../` in basePath solved it. windows 7.

**Comment by Dignifiedquire** [comment]
This is not a bug, but rather how karmas `basePath` works, and how it consequently is used by this plugin.

**Comment by lukeapage** [comment]
@dignifiedquire are you sure? It looks like a bug or at the very least unexpected behaviour..  Setting a particular type of basepath on windows causes coverage to ignore a particular option..  Where is that documented? Or is it a bug in karma? If so do you have a link?

**Comment by Dignifiedquire** [comment]
Sorry, looks like it's not as simple as that..

**Comment by memark** [comment]
+1 for this problem. Really glad I found this issue describing work-arounds.

**Comment by Writtscher** [comment]
Same issue for me on windows. The coverage reports are not generated in the configured folder.

```javascript
var istanbul = require('browserify-istanbul');

module.exports = function(config) {
    config.set({
        basePath: '../../../',
        frameworks: ['browserify', 'mocha', 'sinon-chai'],
        preprocessors: { 'src/main/web/js/**/*.js': ['browserify', 'coverage'] },
        browsers: ['Chrome'],
        reporters: ['progress', 'coverage'],

        autoWatch: true,

        browserify: {
            debug: true,
            transform: [
                istanbul({ ignore: ['**/node_modules/**', '**/test/**'] })
            ]
        },

        coverageReporter: {
            dir : 'build/reports/web/unit/'
        },

        files: [
            'node_modules/angular/angular.min.js',
            'node_modules/angular-mocks/angular-mocks.js',

            'src/main/web/js/main.js',

            'src/test/web/unit/**/*.js'
        ]
    });
};
```

But as soon as is remove the coverage from the preprocessor it works. All files will be generated in the specified folder. This means

```javascript
preprocessors: { 'src/main/web/js/**/*.js': ['browserify'] },
```

**Comment by stevehipwell** [comment]
+1 Same issue here on windows using `basePath: ''`.

**Comment by Ajithsou** [comment]
I am facing the same problem, in my case Absolute path is used as base path. Following is my config file
module.exports = function(config) {
  config.set({
    basePath: 'c:/svn/trunk/myproject/',
    frameworks: ['jasmine', 'requirejs'],
    files: [
      'test-main.js',
      {pattern: 'js/*.js', included: true},
	  {pattern: 'test/*.js', included: true}
    ],
    exclude: [
    ],
    preprocessors: {
		'js/*.js': ['coverage']
    },
    reporters: ['progress','coverage'],
	coverageReporter: {
      type : 'html',
      dir : 'coverage/'
    },
    port: 9876,
    colors: true,
    logLevel: config.LOG_INFO,
    autoWatch: true,
    browsers: ['Chrome'],
	plugins:[
		'karma-jasmine',
		'karma-coverage',
		'karma-chrome-launcher',
		'karma-requirejs'
	],
    singleRun: false
  })
}

Karma modules and its configuration file are in a different folder structure, maintained common for different projects (c:/dev/tools/karma). Each project will have individual karma config. 
Now the coverage report (html) for individual js source files are getting generated in source location itself instead of coverage folder, only the summary coverage reports are in coverage folder.

**Comment by mprentic-harris** [comment]
:+1: we're seeing this issue as well on Windows 7. This wasn't happening a couple weeks ago, but it is happening now using `"karma-coverage": "0.4.2",`

**Comment by codeacula** [comment]
Confirm that `0.4.2` works as expected, but `0.5.x` doesn't on Windows 10.

**Comment by vintem** [comment]
Same problem here on Windows 8, with 0.5.0

**Comment by lebolo** [comment]
I also started having this problem with 0.5.0 (https://github.com/karma-runner/karma-coverage/commit/27e0b09). Was using 0.4.2 before.

**Comment by mbcooper** [comment]
+1 backed down from 0.5.x to 0.4.2

Problems go away!

**Comment by martinoppitz** [comment]
Diff 0.5.x and 0.4.2

**Comment by Ajithsou** [comment]
Uninstall 0.5.x and installed 0.4.2 
It worked

**Comment by bricss** [comment]
+1 for this bug. Does anybody start out planing to fix it?

**Comment by mramato** [comment]
Looking at [the diff](https://github.com/karma-runner/karma-coverage/compare/v0.4.2...v0.5.0) it looks to me like the modifications to `lib/preprocessor.js` are the problem.  It's no longer modifying filepaths to be relative to the output base path and instead is just using the original path of each JS file.  However, I'm not sure what these modifications were intended to fix so I'm not sure if they are the source of the problem or exposing a problem somewhere else.

**Comment by martinoppitz** [comment]
I am sure

**Comment by Zenith-One** [comment]
I can verify that reverting to 0.4.2 fixes the issue.

**Comment by martinoppitz** [comment]
Thank you, that does we already know. The problem is that a newer version is not working properly. We need a better documentation or a fix.

**Comment by bricss** [comment]
Definitely it's a bug, it should resolve paths as all modular systems do.

**Comment by Havunen** [comment]
Reverting to 0.4.2 fixes issue :+1:

**Comment by Dignifiedquire** [comment]
Should be fixed in `0.5.1`

**Comment by samyamirou** [comment]
Hello,

I detect the same issue on versions 0.4.2 and 0.5.1

**Comment by gbreeze** [comment]
Still not working on 0.5.1 and 0.5.3

**Comment by Dignifiedquire** [comment]
@gbreeze please file a new issues with repro

**Comment by jannhama** [comment]
For me this was fixed after all to make small change in the istanbul html reporter (lib/report/html.js). My fork is [here](https://github.com/jannhama/istanbul) not sure if it is universal fix. Worked for me.

**Comment by summanerd** [comment]
I was able to fix this by updating the basepath to use its real path vs the symlink.

Ex:
`basePath: __dirname` changed to `basePath: fs.realpathSync(__dirname)`

the former returned something like 'K:\' vs the real path 'C:\dev\'. It seems that when the other files are pulled in its real path is used. So when istanbul attempts to resolve 'K:\FOLDER_FOR_COVERAGE' & 'C:\dev\FILE_BEING_COVERED' nothing overlaps so it uses 'C:\dev\'.

the goal is to have the absolute path to the coverage as 'C:\dev\FOLDER_FOR_COVERAGE' vs 'K:\FOLDER_FOR_COVERAGE'.

Hope this help!

FYI I'm using Node 6.1.0 - Karma 1.1.2 - Karma Coverage 1.1.1 - Istanbul 0.4.4 on Windows  7
