### ISSUE TITLE
0.2.5 release broke cobertura reports

### ISSUE THREAD

**Issue by mokkabonna** [karma-runner/karma-coverage#91]
Here is my relevant config

```
reporters: ['progress', 'coverage'],
...
coverageReporter: {
  reporters: [{
    type: 'cobertura',
    dir: '.tmp/coverage-report/'
  }, {
    type: 'json',
    dir: 'coverage/'
  }]
},
```

Reverting to 0.2.4 fixes the issue.

**Comment by mdumrauf** [comment]
Still present in 0.2.7. My coverageReporter in karma.config.js looks like this:

```javascript
    coverageReporter: {
      dir: 'coverage/',
      reporters: [
        { type: 'html', subdir: 'report-html' },
        { type: 'text', subdir: '.', file: 'text.txt' },
        { type: 'text-summary', subdir: '.', file: 'text-summary.txt' }
      ]
    },
```

The reports are generated successfully, but no data is output.

**Comment by mdumrauf** [comment]
Never mind. I just realized that if don't specify `subdir` and `file`, they get output.

```javascript
    coverageReporter: {
      dir: 'coverage/',
      reporters: [
        { type: 'html', subdir: 'report-html' },
        { type: 'text' },
        { type: 'text-summary' }
      ]
    },
```

Maybe the docs should be more accurate with this, and also sometimes I would like to have the output on both a file and console.

**Comment by aymericbeaumet** [comment]
That's weird, I think your first configuration should work. I will look into it.

**Comment by nerdgore** [comment]
I can confirm that with the update from 0.2.6 to 0.2.7 karma-coverage now ignores the subdir setting.
